const { contextBridge, ipcRenderer } = require('electron')
contextBridge.exposeInMainWorld('island', {
  getConfig:        ()    => ipcRenderer.invoke('get-config'),
  saveConfig:       (u)   => ipcRenderer.invoke('save-config', u),
  verifyPin:        (p)   => ipcRenderer.invoke('verify-pin', p),
  getDiskStats:     ()    => ipcRenderer.invoke('get-disk-stats'),
  getVaultInfo:     ()    => ipcRenderer.invoke('get-vault-info'),
  saveNote:         (n)   => ipcRenderer.invoke('save-note', n),
  getNotes:         ()    => ipcRenderer.invoke('get-notes'),
  deleteNote:       (id)  => ipcRenderer.invoke('delete-note', id),
  saveFile:         (d)   => ipcRenderer.invoke('save-file', d),
  getFiles:         ()    => ipcRenderer.invoke('get-files'),
  openFile:         (p)   => ipcRenderer.invoke('open-file', p),
  deleteFile:       (n)   => ipcRenderer.invoke('delete-file', n),
  getGallery:       ()    => ipcRenderer.invoke('get-gallery'),
  saveGalleryFile:  (d)   => ipcRenderer.invoke('save-gallery-file', d),
  copyFileToVault:  (d)   => ipcRenderer.invoke('copy-file-to-vault', d),
  convertFile:      (d)   => ipcRenderer.invoke('convert-file', d),
  emergencyWipe:    ()    => ipcRenderer.invoke('emergency-wipe'),
  detectDualBoot:   ()    => ipcRenderer.invoke('detect-dual-boot'),
  mountPartition:   (n)   => ipcRenderer.invoke('mount-partition', n),
  selectFiles:      (o)   => ipcRenderer.invoke('select-files', o),
  getVaultPath:     ()    => ipcRenderer.invoke('get-vault-path'),
  windowMinimize:   ()    => ipcRenderer.invoke('window-minimize'),
  windowMaximize:   ()    => ipcRenderer.invoke('window-maximize'),
  windowClose:      ()    => ipcRenderer.invoke('window-close'),
  onShowLock:       (cb)  => ipcRenderer.on('show-lock', (e, v) => cb(v)),
  onVaultMounted:   (cb)  => ipcRenderer.on('vault-mounted', (e, v) => cb(v))
})
